### ISSUE TITLE
Hol

### ISSUE THREAD

**Issue by DaGov** [makertum/Trinamic_TMC2130#6]
After I power on, my motors is hold on.
And how I can change CS pins in Marlin?

**Comment by DaGov** [comment]
And when i put M84 (disable steppers) my motors hold on.

**Comment by makertum** [comment]
Hi DaGov,

thanks for reaching out. The information you're giving me here is rather sparse, but this I can say:

- You can change the CS pins in Marlin in the pins_yourBoardType.h file
- M84: That is the expected behavior of the command.

Besides that, please don't clutter the issue tracking in this repository with support questions about Marlin. Marlin is awesome, and I'll be glad to help, but please shoot me an email instead.

Thanks,
Moritz
